In [9]:
import pandas as pd

from libs.statical_analysis import AdjustedTtestSelection
from libs.statical_analysis import OneWayAnova
from libs.utils import get_mean_dataset

import warnings
warnings.filterwarnings('ignore')

In [10]:
cd C:\Users\tr432\Downloads\Metabolomics_GutLungAxis_re-pipeline

C:\Users\tr432\Downloads\Metabolomics_GutLungAxis_re-pipeline

In [11]:
# if you want to select the features by comparing two groups, you should use "AdjustedTtestSelection"
# if you want to analyze the multiple groups (more than two), you should use  "OneWayAnova"

# AdjustedTtestSelection is the method of Benjamini-Hochberg procedure (Adjusted T-test)
# OneWayAnova includes the post hoc test of Bonferroni


# First, this is example of two group analysis

feature_selection = AdjustedTtestSelection(
    fc_threshold=2.0,
    p_value_threshold=0.05,
    fdr_threshold=0.05,
    is_save_file=True
)

# preparing dataset (recommend for using filtered dataset)
df_ori_total = pd.read_csv('dataset_filtered.csv')

# select the two groups(label)
df_ori_twogroup = df_ori_total[df_ori_total.Label.isin(['Control', 'VNAM'])].reset_index(drop=True)

In [12]:
# The hyperparameter "scaled_dataset" in feature_selection is optional.
# it is just designated to be saved together with final saved file.

df_static, df_selection = feature_selection.feature_selection(ori_dataset=df_ori_twogroup)
df_static.head()

The mean of 247.00112-8.613 is zero in any one group...
The mean of 546.4887-16.579 is zero in any one group...
The mean of 391.34206-17.367 is zero in any one group...
feature_selection.xlsx file is saved

,feature,Control_mean,VNAM_mean,Fold_change,Control_shaprio,VNAM_shaprio,p_value,FDR_values
0,61.03969-1.062,9.522415e+08,1.424819e+09,0.668324,5.246914e-01,0.489934,0.026287,0.085726
1,496.33995-14.389,1.481204e+09,1.328070e+09,1.115305,5.172863e-01,0.034127,0.289705,0.458974
2,172.07169-4.382,4.251696e+04,8.872328e+08,0.000048,3.217493e-07,0.079681,0.036870,0.108983
3,520.34-13.811,1.050332e+09,1.014417e+09,1.035405,7.789629e-01,0.118175,0.816205,0.891326
4,73.06478-1.434,1.925923e+08,1.381762e+08,1.393817,3.906181e-01,0.702451,0.358149,0.534031

In [7]:
# Oneway anova analysis
# more than two Label (eg, control, sefere, mild...)

df_ori_total = pd.read_csv('dataset_filtered.csv')
print(df_ori_total.Label.unique())

['Control' 'VNAM']

In [5]:
anova = OneWayAnova(
    is_save_file=True,
    p_value=0.05,
)

df_anova = anova.processing(df_ori_total)
df_anova.head()

oneway_analysis.xlsx file is saved

,one-way_pvalue,Control_Severe,Control_Moderate,Control_Mild,Severe_Moderate,Severe_Mild,Moderate_Mild
0.5_201.8884,0.745250,1.00000,1.0,1.0,1.000000,1.000000,1.000000
0.5_230.8912,0.092301,1.00000,1.0,1.0,1.000000,0.059695,0.320858
0.51_170.9287,0.541336,1.00000,1.0,1.0,1.000000,1.000000,1.000000
0.51_182.9633,0.042624,0.04831,1.0,1.0,0.232479,0.172111,1.000000
0.51_214.9182,0.530117,1.00000,1.0,1.0,1.000000,1.000000,1.000000

In [6]:
# If you want to check the average intensity of features according to label, you can perform the "get_mean_dataset"

df_mean = get_mean_dataset(
    dataset=df_ori_total,
    label_list=['Control', 'Severe', 'Moderate', 'Mild']
)

df_mean.head()

                    Control         Severe       Moderate          Mild
0.5_201.8884      509.53670     501.570145     596.372305     463.51990
0.5_230.8912     1257.74302    1573.254175    1434.037685    1078.90875
0.51_170.9287    7681.95440    7553.897600    8133.845250    7623.29675
0.51_182.9633   13656.83160   11289.300050   13294.807800   13329.41165
0.51_214.9182  333859.59000  323926.155000  347818.690000  333904.11500